### ISSUE TITLE
Example doesn't load

### ISSUE THREAD

**Issue by ebrelsford** [maptime/maptime-bites#2]
The [example linked to](http://bl.ocks.org/geografa/9149592) doesn't load for me ("File not found").

**Comment by geografa** [comment]
Thanks...which bite was this for?

**Comment by jqtrde** [comment]
Looks like it's for the example in the README

**Comment by geografa** [comment]
:+1: https://github.com/maptime/maptime-bites/commit/a45d4ccd6d14

**Comment by ebrelsford** [comment]
Oh yeah, sorry I wasn't more clear! Thanks.
