### ISSUE TITLE
link to tilejson in bite 0002 is dead

### ISSUE THREAD

**Issue by skorasaurus** [maptime/maptime-bites#22]
http://maptime.io/maptime-bites/00002/ doesn't display any tiles because http://a.tiles.mapbox.com/v3/grafa.6ebnvcxr.json returns a 404. 

cc @geografa

**Comment by geografa** [comment]
:) just noticed that, too! Fixing...

**Comment by geografa** [comment]
https://github.com/maptime/maptime-bites/commit/e13074d1b2a02e84ab4b6c433ecf41a68a73bcf3
