### ISSUE TITLE
Swap water color base map

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-bites#9]
Let's see what we can get for a new map. Possibly host on someone's Mapbox account or elsewhere ;)

Reason being it would be nice to have some context (city/country labels) and a custom map that shows some new custom coolness.

**Comment by smathermather** [comment]
How about something like this (a compromise between practical and artistic:

http://{s}.sm.mapstack.stamen.com/(toner-lite,(watercolor,$fff%5B@0%5D,$fff%5Bhsl-saturation@50%5D,mapbox-water%5Bdestination-in%5D)%5B@50%5D/{z}/{x}/{y}.png

![tile](https://cloud.githubusercontent.com/assets/1174901/3086607/5995b126-e53c-11e3-89ea-a9c98ed7136a.png)

**Comment by geografa** [comment]
@smathermather I like it. That looks like some kind of composited tileLayer. Is there a link?

**Comment by bethschechter** [comment]
yummy! hooray for paper texture

PS the site is looking great. I'm sorry I've been slow to check out prose.io.
in the middle of a move. thanks to everyone who's putting so much work into
this!

On Wed, May 28, 2014 at 10:30 PM, geografa notifications@github.com wrote:

> @smathermather https://github.com/smathermather I like it. That looks
> like some kind of composited tileLayer. Is there a link?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maptime/maptime-bites/issues/9#issuecomment-44495941.

## 

Beth Schechter, Education + Outreach
Stamen Design, LLC
http://stamen.com/
+1 (415) 558-1610

**Comment by smathermather** [comment]
Hi @geografa, there sure is:

http://{s}.sm.mapstack.stamen.com/(toner-lite,(watercolor,$fff%5B@0%5D,$fff%5Bhsl-saturation@50%5D,mapbox-water%5Bdestination-in%5D)%5B@50%5D/{z}/{x}/{y}.png .

**Comment by geografa** [comment]
:+1: I swapped the marker out, too, but not sure I like it. Eventually, I'd like to use marker clustering. Anyways, thanks for the layer.

**Comment by smathermather** [comment]
NP
